import { useListNovels } from "@workspace/api-client-react";
import { Link } from "wouter";
import { motion } from "framer-motion";
import { Plus, Search, BookMarked, Sparkles } from "lucide-react";
import { useState } from "react";
import { format } from "date-fns";

export default function Home() {
  const [search, setSearch] = useState("");
  const { data: response, isLoading } = useListNovels({ search, limit: 50 });

  const novels = response?.novels || [];

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex-1 flex flex-col"
    >
      {/* Hero Section */}
      <section className="relative pt-24 pb-32 overflow-hidden flex-shrink-0">
        <div className="absolute inset-0 z-0">
          <img 
            src={`${import.meta.env.BASE_URL}images/hero-bg.png`} 
            alt="Library background" 
            className="w-full h-full object-cover opacity-20"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/80 to-background"></div>
        </div>
        
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.h1 
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.1 }}
            className="text-5xl md:text-7xl font-serif font-bold tracking-tight text-foreground mb-6"
          >
            Your Library of <br className="hidden md:block"/>
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-primary/60">Infinite Stories</span>
          </motion.h1>
          <motion.p 
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10"
          >
            Create, manage, and read immersive novels generated by advanced AI. 
            Shape the narrative or let the intelligence guide the way.
          </motion.p>
          <motion.div 
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <Link 
              href="/novels/new" 
              className="flex items-center gap-2 px-8 py-4 rounded-full bg-primary text-primary-foreground font-medium shadow-lg shadow-primary/25 hover:shadow-xl hover:shadow-primary/40 hover:-translate-y-0.5 transition-all duration-300"
            >
              <Sparkles className="w-4 h-4" />
              Start a New Novel
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Library Section */}
      <section className="relative z-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24 -mt-12">
        <div className="flex flex-col md:flex-row justify-between items-end md:items-center gap-6 mb-12">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-card border border-border flex items-center justify-center shadow-sm">
              <BookMarked className="w-5 h-5 text-primary" />
            </div>
            <h2 className="text-3xl font-serif font-semibold">Your Collection</h2>
          </div>
          
          <div className="relative w-full md:w-72">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <input 
              type="text"
              placeholder="Search novels..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-card border border-border/50 rounded-full focus:outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all text-sm"
            />
          </div>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {[1,2,3,4].map(i => (
              <div key={i} className="animate-pulse flex flex-col gap-4">
                <div className="aspect-[3/4] bg-muted rounded-2xl"></div>
                <div className="h-6 bg-muted rounded w-3/4"></div>
                <div className="h-4 bg-muted rounded w-1/2"></div>
              </div>
            ))}
          </div>
        ) : novels.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6 gap-y-10">
            {novels.map((novel, i) => (
              <Link key={novel.id} href={`/novels/${novel.id}`} className="group cursor-pointer outline-none">
                <motion.div 
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="relative flex flex-col h-full"
                >
                  <div className="relative aspect-[3/4] rounded-xl overflow-hidden mb-4 shadow-xl shadow-black/10 transition-transform duration-500 group-hover:-translate-y-2 group-focus-visible:-translate-y-2 group-hover:shadow-2xl group-hover:shadow-primary/20">
                    <img 
                      src={novel.coverImage || `${import.meta.env.BASE_URL}images/cover-placeholder.png`} 
                      alt={novel.title}
                      className="w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-60 group-hover:opacity-40 transition-opacity duration-300"></div>
                    
                    <div className="absolute top-3 left-3 flex flex-wrap gap-2">
                      <span className="px-2.5 py-1 text-xs font-medium bg-background/90 backdrop-blur-sm text-foreground rounded-full border border-border/50">
                        {novel.genre}
                      </span>
                    </div>
                    
                    <div className="absolute bottom-3 left-3 right-3 flex justify-between items-center">
                      <span className="text-xs font-medium text-white/90 bg-black/40 backdrop-blur-md px-2 py-1 rounded-md">
                        {novel.chapterCount} Chapters
                      </span>
                      <span className="text-xs font-medium text-white/90 bg-black/40 backdrop-blur-md px-2 py-1 rounded-md capitalize">
                        {novel.status.replace('_', ' ')}
                      </span>
                    </div>
                  </div>
                  
                  <h3 className="font-serif font-bold text-lg leading-tight mb-1 group-hover:text-primary transition-colors line-clamp-2">
                    {novel.title}
                  </h3>
                  <p className="text-sm text-muted-foreground mt-auto">
                    Updated {format(new Date(novel.updatedAt), "MMM d, yyyy")}
                  </p>
                </motion.div>
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-32 border-2 border-dashed border-border/50 rounded-3xl bg-card/30 backdrop-blur-sm">
            <BookMarked className="w-12 h-12 text-muted-foreground mx-auto mb-4 opacity-50" />
            <h3 className="text-xl font-serif font-semibold mb-2">No novels found</h3>
            <p className="text-muted-foreground mb-6">You haven't created any stories yet, or none match your search.</p>
            <Link 
              href="/novels/new" 
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-secondary text-secondary-foreground font-medium hover:bg-secondary/80 transition-colors"
            >
              <Plus className="w-4 h-4" />
              Create First Novel
            </Link>
          </div>
        )}
      </section>
    </motion.div>
  );
}
